import 'package:whes_tablet_app/classes/heritage.dart';

class HeritageData extends Heritage {
  static final List<Heritage> items = [
    Heritage(
        titleDetail: "title_bellinzona",
        urlDetail: "assets/images/headers/Castelgrande2.jpg",
        title1: "title1_bellinzona",
        text1: "text1_bellinzona",
        text2: "text2_bellinzona",
        text3: "text3_bellinzona",
        bottomIcon: 105,
        rightIcon: 390,
        urlIcon: "assets/images/icons/bellinzona.png",
        titlePopUp: "title_bellinzona",
        textPopUp: "since_bellinzona",
        urlPopUp: "assets/images/headers/Castelgrande2.jpg",
        urlQR: "assets/images/qr/bellinzona.png",
        heritageGallery: <String>[
          "assets/images/heritage/bellinzona1.jpg",
          "assets/images/heritage/bellinzona2.jpg",
          "assets/images/heritage/bellinzona3.jpg",
          "assets/images/heritage/bellinzona4.jpg"
        ]),
    Heritage(
        titleDetail: "title_bahn",
        urlDetail: "assets/images/headers/bahn.jpg",
        title1: "title1_bahn",
        text1: "text1_bahn",
        text2: "text2_bahn",
        text3: "text3_bahn",
        bottomIcon: 215,
        rightIcon: 190,
        urlIcon: "assets/images/icons/albula_bernina.png",
        titlePopUp: "title_bahn",
        textPopUp: "since_bahn",
        urlPopUp: "assets/images/headers/bahn.jpg",
        urlQR: "assets/images/qr/bahn.png",
        heritageGallery: <String>[
          "assets/images/heritage/bahn1.jpg",
          "assets/images/heritage/bahn2.jpg",
          "assets/images/heritage/bahn3.jpg",
          "assets/images/heritage/bahn4.jpg",
          "assets/images/heritage/bahn5.jpg",
          "assets/images/heritage/bahn6.jpg",
          "assets/images/heritage/bahn7.jpg"
        ]),
    Heritage(
        titleDetail: "title_bern",
        urlDetail: "assets/images/headers/bern.jpg",
        title1: "title1_bern",
        text1: "text1_bern",
        text2: "text2_bern",
        text3: "text3_bern",
        bottomIcon: 370,
        rightIcon: 810,
        urlIcon: "assets/images/icons/bern.png",
        titlePopUp: "title_bern",
        textPopUp: "since_bern",
        urlPopUp: "assets/images/headers/bern.jpg",
        urlQR: "assets/images/qr/bern.png",
        heritageGallery: <String>[
          "assets/images/heritage/bern1.jpg",
          "assets/images/heritage/bern2.jpg",
          "assets/images/heritage/bern3.jpg",
        ]),
    Heritage(
        titleDetail: "title_chaux",
        urlDetail: "assets/images/headers/la_chaux_de_fonds.jpg",
        title1: "title1_chaux",
        text1: "text1_chaux",
        text2: "text2_chaux",
        text3: "text3_chaux",
        bottomIcon: 440,
        rightIcon: 970,
        urlIcon: "assets/images/icons/chaux_de_fonds.png",
        titlePopUp: "title_chaux",
        textPopUp: "since_chaux",
        urlPopUp: "assets/images/headers/la_chaux_de_fonds.jpg",
        urlQR: "assets/images/qr/chaux.png",
        heritageGallery: <String>[
          "assets/images/heritage/chaux1.jpg",
          "assets/images/heritage/chaux2.jpg",
          "assets/images/heritage/chaux3.jpg",
          "assets/images/heritage/chaux4.jpg"
        ]),
    Heritage(
        titleDetail: "title_corbusier",
        urlDetail: "assets/images/headers/le_corbusier.jpg",
        title1: "title1_corbusier",
        text1: "text1_corbusier",
        text2: "text2_corbusier",
        text3: "text3_corbusier",
        bottomIcon: 205,
        rightIcon: 975,
        urlIcon: "assets/images/icons/corbusier.png",
        titlePopUp: "title_corbusier",
        textPopUp: "since_corbusier",
        urlPopUp: "assets/images/headers/le_corbusier.jpg",
        urlQR: "assets/images/qr/corbusier.png",
        heritageGallery: <String>[
          "assets/images/heritage/corbusier1.jpg",
          "assets/images/heritage/corbusier2.jpg",
          "assets/images/heritage/corbusier3.jpg",
          "assets/images/heritage/corbusier4.jpg",
          "assets/images/heritage/corbusier5.jpg"
        ]),
    Heritage(
        titleDetail: "title_alpen",
        urlDetail: "assets/images/headers/aletsch.jpg",
        title1: "title1_alpen",
        text1: "text1_alpen",
        text2: "text2_alpen",
        text3: "text3_alpen",
        bottomIcon: 200,
        rightIcon: 660,
        urlIcon: "assets/images/icons/jungfrau_aletsch.png",
        titlePopUp: "title_alpen",
        textPopUp: "since_alpen",
        urlPopUp: "assets/images/headers/aletsch.jpg",
        urlQR: "assets/images/qr/alpen.png",
        heritageGallery: <String>[
          "assets/images/heritage/alps1.jpg",
          "assets/images/heritage/alps2.jpg",
          "assets/images/heritage/alps3.jpg",
          "assets/images/heritage/alps4.jpg",
          "assets/images/heritage/alps5.jpg",
          "assets/images/heritage/alps6.jpg",
          "assets/images/heritage/alps7.jpg",
          "assets/images/heritage/alps8.jpg"
        ]),
    Heritage(
        titleDetail: "title_lavaux",
        urlDetail: "assets/images/headers/lavaux.jpg",
        title1: "title1_lavaux",
        text1: "text1_lavaux",
        text2: "text2_lavaux",
        text3: "text3_lavaux",
        bottomIcon: 215,
        rightIcon: 1025,
        urlIcon: "assets/images/icons/lavaux.png",
        titlePopUp: "title_lavaux",
        textPopUp: "since_lavaux",
        urlPopUp: "assets/images/headers/lavaux.jpg",
        urlQR: "assets/images/qr/lavaux.png",
        heritageGallery: <String>[
          "assets/images/heritage/lavaux1.jpg",
          "assets/images/heritage/lavaux2.jpg",
          "assets/images/heritage/lavaux3.jpg",
          "assets/images/heritage/lavaux4.jpg"
        ]),
    Heritage(
        titleDetail: "title_mustair",
        urlDetail: "assets/images/headers/mustair.jpg",
        title1: "title1_mustair",
        text1: "text1_mustair",
        text2: "text2_mustair",
        text3: "text3_mustair",
        bottomIcon: 250,
        rightIcon: 45,
        urlIcon: "assets/images/icons/mustair.png",
        titlePopUp: "title_mustair",
        textPopUp: "since_mustair",
        urlPopUp: "assets/images/headers/mustair.jpg",
        urlQR: "assets/images/qr/mustair.png",
        heritageGallery: <String>[
          "assets/images/heritage/mustair1.jpg",
          "assets/images/heritage/mustair2.jpg",
          "assets/images/heritage/mustair3.jpg",
          "assets/images/heritage/mustair4.jpg"
        ]),
    Heritage(
        titleDetail: "title_pfahlbauten",
        urlDetail: "assets/images/headers/pfahlbauten.jpg",
        title1: "title1_pfahlbauten",
        text1: "text1_pfahlbauten",
        text2: "text2_pfahlbauten",
        text3: "text3_pfahlbauten",
        bottomIcon: 400,
        rightIcon: 935,
        urlIcon: "assets/images/icons/pfahlbauten.png",
        titlePopUp: "title_pfahlbauten",
        textPopUp: "since_pfahlbauten",
        urlPopUp: "assets/images/headers/pfahlbauten.jpg",
        urlQR: "assets/images/qr/pfahlbauten.png",
        heritageGallery: <String>[
          "assets/images/heritage/pfahlbauten1.jpg",
          "assets/images/heritage/pfahlbauten2.jpg",
          "assets/images/heritage/pfahlbauten3.jpg",
          "assets/images/heritage/pfahlbauten4.jpg",
          "assets/images/heritage/pfahlbauten5.jpg",
          "assets/images/heritage/pfahlbauten6.jpg",
          "assets/images/heritage/pfahlbauten7.jpg",
          "assets/images/heritage/pfahlbauten8.jpg"
        ]),
    Heritage(
        titleDetail: "title_monte",
        urlDetail: "assets/images/headers/monte.jpg",
        title1: "title1_monte",
        text1: "text1_monte",
        text2: "text2_monte",
        text3: "text3_monte",
        bottomIcon: 10,
        rightIcon: 425,
        urlIcon: "assets/images/icons/san_giorgio.png",
        titlePopUp: "title_monte",
        textPopUp: "since_monte",
        urlPopUp: "assets/images/headers/monte.jpg",
        urlQR: "assets/images/qr/monte.png",
        heritageGallery: <String>[
          "assets/images/heritage/monte1.jpg",
          "assets/images/heritage/monte2.jpg",
          "assets/images/heritage/monte3.jpg",
          "assets/images/heritage/monte4.jpg",
          "assets/images/heritage/monte5.jpg",
          "assets/images/heritage/monte6.jpg",
          "assets/images/heritage/monte7.jpg",
          "assets/images/heritage/monte8.jpg",
        ]),
    Heritage(
        titleDetail: "title_arena",
        urlDetail: "assets/images/headers/arena.jpg",
        title1: "title1_arena",
        text1: "text1_arena",
        text2: "text2_arena",
        text3: "text3_arena",
        bottomIcon: 360,
        rightIcon: 355,
        urlIcon: "assets/images/icons/sardona.png",
        titlePopUp: "title_arena",
        textPopUp: "since_arena",
        urlPopUp: "assets/images/headers/arena.jpg",
        urlQR: "assets/images/qr/arena.png",
        heritageGallery: <String>[
          "assets/images/heritage/sardona1.jpg",
          "assets/images/heritage/sardona2.jpg",
          "assets/images/heritage/sardona3.jpg",
          "assets/images/heritage/sardona4.jpg",
          "assets/images/heritage/sardona5.jpg",
          "assets/images/heritage/sardona6.jpg",
          "assets/images/heritage/sardona7.jpg",
          "assets/images/heritage/sardona8.jpg",
        ]),
    Heritage(
        titleDetail: "title_gallen",
        urlDetail: "assets/images/headers/st_gallen.jpg",
        title1: "title1_gallen",
        text1: "text1_gallen",
        text2: "text2_gallen",
        text3: "text3_gallen",
        bottomIcon: 565,
        rightIcon: 310,
        urlIcon: "assets/images/icons/st_gallen.png",
        titlePopUp: "title_gallen",
        textPopUp: "since_gallen",
        urlPopUp: "assets/images/headers/st_gallen.jpg",
        urlQR: "assets/images/qr/st_gallen.png",
        heritageGallery: <String>[
          "assets/images/heritage/stgallen1.jpg",
          "assets/images/heritage/stgallen2.jpg",
          "assets/images/heritage/stgallen3.jpg",
          "assets/images/heritage/stgallen4.jpg",
          "assets/images/heritage/stgallen5.jpg",
        ])
  ];
  static Heritage fetchAny() {
    return HeritageData.items[0];
  }

  static List<Heritage> fetchAll() {
    return HeritageData.items;
  }
}
